# Production values for linkerd-mcp
# This file contains recommended settings for production deployments

replicaCount: 3

image:
  repository: linkerd-mcp
  pullPolicy: IfNotPresent
  tag: ""  # Use chart appVersion

podAnnotations:
  linkerd.io/inject: "enabled"

# Enhanced security for production
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
  fsGroup: 65532
  fsGroupChangePolicy: "OnRootMismatch"
  seccompProfile:
    type: RuntimeDefault

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
  seccompProfile:
    type: RuntimeDefault

service:
  enabled: true
  type: ClusterIP
  port: 8080
  targetPort: 8080
  protocol: TCP

# Production resource allocation
resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

# Enable autoscaling for production
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

# Enable pod disruption budget
podDisruptionBudget:
  enabled: true
  minAvailable: 2

# Enable network policies for defense in depth
networkPolicy:
  enabled: true
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow ingress from Linkerd mesh
    - from:
      - namespaceSelector:
          matchLabels:
            linkerd.io/is-control-plane: "false"
      ports:
      - protocol: TCP
        port: 8080
  egress:
    # Allow DNS
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
      ports:
      - protocol: UDP
        port: 53
    # Allow Kubernetes API
    - to:
      - namespaceSelector: {}
        podSelector:
          matchLabels:
            component: apiserver
      ports:
      - protocol: TCP
        port: 443
    - ports:
      - protocol: TCP
        port: 6443

# Topology spread for high availability
topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: linkerd-mcp
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: linkerd-mcp

# Anti-affinity for pod distribution
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: linkerd-mcp
        topologyKey: kubernetes.io/hostname

# Update strategy for zero-downtime deployments
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

# Keep more history for rollbacks
revisionHistoryLimit: 10

# Production environment variables
env:
  - name: LINKERD_NAMESPACE
    value: "linkerd"

# Priority class for critical workloads (uncomment and configure if needed)
# priorityClassName: "high-priority"
